services:
  ai-service:
    image: registry.digitalocean.com/family-recipe-ai/family-recipe-ai:latest
    container_name: family-recipe-ai
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - TZ=America/Los_Angeles
      - ENVIRONMENT=production
      - HOST=0.0.0.0
      - PORT=8000
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
